### ISSUE TITLE
If user inputs an invalid API key it should return the header title/detail when requesting

### ISSUE THREAD

**Issue by brown-jason** [USEPA/ctxR#32]
If you input an invalid API key ctxR will respond with:
"  Please input an API_key!"

Ideally it would respond with one or both of the following messages from the header.
{
  "title": "API Key Not Found",
  "detail": "Please contact API admin for requesting a valid API key. Key xxxxxxxxxx not found."
}

The only time ctxR should return "  Please input an API_key!" is when the user has not specified an api key at all.

**Comment by rachmaninoffpk** [comment]
I will include the detail portion of the response. That gives a sufficient amount of information.
