### ISSUE TITLE
Update Chemical API batch search vignette example

### ISSUE THREAD

**Issue by madison-feshuk** [USEPA/ctxR#4]
Based on user feedback, let's update Chemical API vignette to include a more straightforward batch search example. Additional filtering parameters (i.e. ability to search by CAS, SMILES, Name, etc. may be coming in the future)

1. Under Chemical Details resource, add batch search subsection, ex. list of dtxsids
list_dtxsid<- list("DTXSID7020182", "DTXSID9020112", "DTXSID8021430")

2. Rename "Access Physico-chemical Property Data for Chemical Lists" as "Batch Search Physico-chemical Property Data by DTXSID for Chemical Lists"

**Comment by ucb** [comment]
Which function is it that allows search by CAS? It is not included in the library documentation...

**Comment by madison-feshuk** [comment]
@ucb Hello, you can use the functions described under the Chemical Search Resource section here: https://cran.r-project.org/web/packages/ctxR/vignettes/Chemical.html

Ex.  search_exact <- chemical_equal('80-05-7')

We will update the documentation to reflect flexibility here. Thanks!
